name: 06 - Contexts
on: 
  push:
  workflow_dispatch:
jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
    - name: Display Information
      run: |
        echo "Event name: ${{ vars.GITHUB_EVENT_NAME }}"
        echo "Ref: ${{ vars.GITHUB_WORKFLOW_SHA }}"
        echo "SHA: ${{ vars.GITHUB_SHA }}"
        echo "Actor: ${{ vars.GITHUB_ACTOR }}"
        echo "Workflow: ${{ vars.GITHUB_WORKFLOW }}"
        echo "Run ID: ${{ vars.GITHUB_RUN_ID }}"
        echo "Run number: ${{ vars.GITHUB_RUN_NUMBER }}"

    - name: Retrieve Variable
      run: echo ${{ vars.MY_VAR }}
        