name: 11 - Working with Inputs
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Skip deployment and only print build output"
        type: boolean
        default: false
      target:
        type: environment
        description: "Which environment the workflow will target"
      tag:
        type: choice
        options:
          - v1
          - v2
          - v3
        default: v3
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "Building from tag $GITHUB_REF"
  deploy:
    if: ${{ success() && github.events.inputs.dry-run == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "Deploying to ${{ github.actions.inputs.target }}"
    env:
      target: environment